### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by z-snake** [auth12/sysmap#2]
crash on windows 7

**Comment by auth12** [comment]
Please provide more information

**Comment by z-snake** [comment]
this is the problem.
<img src="https://cdn.discordapp.com/attachments/647932102444187651/864803475808190534/qwqw.PNG"></img>

**Comment by z-snake** [comment]
problem with resolving imports.

**Comment by auth12** [comment]
Breakpoint it and step through the code, I cannot do anything with the information you gave me. Show me debugger information or something. I dont have w7 or crossfire.
